### ISSUE TITLE
Error in mongo express in docker

### ISSUE THREAD

**Issue by Nexa-speech** [Saniewski/mongo-express-docker-extension#50]
"Service Unavailable
Please, make sure the credentials are correct or try again after restarting / reinstalling the extension.
If the problem persists, please create an issue on the extension's GitHub page."

I always get this error. I copy past my Mongodb connection string from mongo atlas and change the <password> accordingly and I always receive the mentioned error.

<img width="1266" alt="image" src="https://github.com/Saniewski/mongo-express-docker-extension/assets/132650972/f0e9cbec-f94a-4fae-9f44-b3fc47b8ecc3">

**Comment by Saniewski** [comment]
Hello! Thank you for reporting the issue!

This is a known bug in Mongo Express itself. I am tracking this bug since Feb 3 here: #39 

I'm afraid it's impossible to use Mongo Express Docker Extension v1.0.2 to connect to Mongo Atlas.

For now, please, follow the main issue entry for this bug (#39).
